### ISSUE TITLE
how get start_videoframe=16?

### ISSUE THREAD

**Issue by www516717402** [pluckpeng/Audio2Face#3]
Thank you for open this repo.
1.  The audio and BS is align when collect. Why is it aligned again?

2.  When audio length not align with BS,  how get start_videoframe=16?

https://github.com/pluckpeng/Audio2Face/blob/eec4fdc0b33392b4705798050c709382f2a6bd6c/dataset.py#L52-L54

**Comment by pluckpeng** [comment]
1. The thing is, the competition I took offered me those BS which is not aligned with the audio clip given. Besides, the FPS could be customized because the sample rate you choose to read in the audio clip is not fixed. By changing the sample rate you will get different FPS.
2. 16 is not fixed.
https://github.com/pluckpeng/Audio2Face/blob/eec4fdc0b33392b4705798050c709382f2a6bd6c/dataset.py#L51
Mostly the BS frame is more than the audio frame. So when it happens, we need to cut the equal amounts of frames from the BS frames. The start_videoframe should less than 40 according to the assertion. I choose 16 is just because the FPS is 16. You can design it with a particular number.

**Comment by www516717402** [comment]
Than you for reply. 
1. about issue-2 same as [code](https://github.com/zhongshaoyy/Audio2Face/blob/1ea9cb478ad728567fc4397c16ef3e5a875b8e3a/dataset.py#L24)，However  across overlap and padding to align frame count. in facegood LPC. In train step, you can cut data to any shape and align to label, but in inference, input a video and split it to picture and audio, how to align frame count with output blend shape?
2. Loss convergence bad when use multi dataset and get huge bias which predict in train data. Have you meet this issue?
3. Any email for concat you ?  I also get some competition dataset meet some problem.
